In [7]:
import itertools
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import NullFormatter
import pandas as pd
import numpy as np
import matplotlib.ticker as ticker
from sklearn import preprocessing
%matplotlib inline

In [8]:
my_data = pd.read_csv("sample-data.csv", delimiter=",")
my_data[0:22]

date         home_team         away_team  home_score  away_score  \
0   1872-11-30          Scotland           England           0           0   
1   1873-03-08           England          Scotland           4           2   
2   1874-03-07          Scotland           England           2           1   
3   1875-03-06           England          Scotland           2           2   
4   1876-03-04          Scotland           England           3           0   
5   1876-03-25          Scotland             Wales           4           0   
6   1877-03-03           England          Scotland           1           3   
7   1877-03-05             Wales          Scotland           0           2   
8   1878-03-02          Scotland           England           7           2   
9   1878-03-23          Scotland             Wales           9           0   
10  1879-01-18           England             Wales           2           1   
11  1879-04-05           England          Scotland           5           4   
12  1879-04-07             Wales          Scotland           0           3   
13  1880-03-13          Scotland           England           5           4   
14  1880-03-15             Wales           England           2           3   
15  1880-03-27          Scotland             Wales           5           1   
16  1881-02-26           England             Wales           0           1   
17  1881-03-12           England          Scotland           1           6   
18  1881-03-14             Wales          Scotland           1           5   
19  1882-02-18  Northern Ireland           England           0          13   
20  1882-02-25             Wales  Northern Ireland           7           1   
21  1882-03-11          Scotland           England           5           1   

   tournament       city              country  neutral  
0    Friendly    Glasgow             Scotland        0  
1    Friendly     London              England        0  
2    Friendly    Glasgow             Scotland        0  
3    Friendly     London              England        0  
4    Friendly    Glasgow             Scotland        0  
5    Friendly    Glasgow             Scotland        0  
6    Friendly     London              England        0  
7    Friendly    Wrexham                Wales        0  
8    Friendly    Glasgow             Scotland        0  
9    Friendly    Glasgow             Scotland        0  
10   Friendly     London              England        0  
11   Friendly     London              England        0  
12   Friendly    Wrexham                Wales        0  
13   Friendly    Glasgow             Scotland        0  
14   Friendly    Wrexham                Wales        0  
15   Friendly    Glasgow             Scotland        0  
16   Friendly  Blackburn              England        0  
17   Friendly     London              England        0  
18   Friendly    Wrexham                Wales        0  
19   Friendly    Belfast  Republic of Ireland        0  
20   Friendly    Wrexham                Wales        0  
21   Friendly    Glasgow             Scotland        0

In [9]:
my_data['neutral'].value_counts()

0    31304
1    10282
Name: neutral, dtype: int64

In [10]:
X = my_data[['home_score', 'away_score']] .values  #.astype(float)
X[0:12]

array([[0, 0],
       [4, 2],
       [2, 1],
       [2, 2],
       [3, 0],
       [4, 0],
       [1, 3],
       [0, 2],
       [7, 2],
       [9, 0],
       [2, 1],
       [5, 4]], dtype=int64)

In [11]:
y = my_data['neutral'].values
y[0:21]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [12]:
X = preprocessing.StandardScaler().fit(X).transform(X.astype(float))
X[0:21]

array([[-0.99543639, -0.84507338],
       [ 1.28537837,  0.57810363],
       [ 0.14497099, -0.13348487],
       [ 0.14497099,  0.57810363],
       [ 0.71517468, -0.84507338],
       [ 1.28537837, -0.84507338],
       [-0.4252327 ,  1.28969213],
       [-0.99543639,  0.57810363],
       [ 2.99598945,  0.57810363],
       [ 4.13639683, -0.84507338],
       [ 0.14497099, -0.13348487],
       [ 1.85558206,  2.00128064],
       [-0.99543639,  1.28969213],
       [ 1.85558206,  2.00128064],
       [ 0.14497099,  1.28969213],
       [ 1.85558206, -0.13348487],
       [-0.99543639, -0.13348487],
       [-0.4252327 ,  3.42445764],
       [-0.4252327 ,  2.71286914],
       [-0.99543639,  8.40557717],
       [ 2.99598945, -0.13348487]])

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=20)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (33268, 2) (33268,)
Test set: (8318, 2) (8318,)


In [14]:
from sklearn.neighbors import KNeighborsClassifier

In [15]:
k = 4
#Train Model and Predict  
neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
neigh

KNeighborsClassifier(n_neighbors=4)

In [16]:
yhat = neigh.predict(X_test)
yhat[0:50]

array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1], dtype=int64)

In [17]:
from sklearn import metrics
print("Train set Accuracy: ", metrics.accuracy_score(y_train, neigh.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, yhat))

Train set Accuracy:  0.6935794156546832
Test set Accuracy:  0.6945179129598461


In [19]:
Ks = 10
mean_acc = np.zeros((Ks-1))
std_acc = np.zeros((Ks-1))
ConfustionMx = [];
for n in range(1,Ks):
    
    #Train Model and Predict  
    neigh = KNeighborsClassifier(n_neighbors = n).fit(X_train,y_train)
    yhat=neigh.predict(X_test)
    mean_acc[n-1] = metrics.accuracy_score(y_test, yhat)

    
    std_acc[n-1]=np.std(yhat==y_test)/np.sqrt(yhat.shape[0])

mean_acc

array([0.58307285, 0.62454917, 0.61517192, 0.69451791, 0.69018995,
       0.7012503 , 0.69415725, 0.69908632, 0.69920654])

In [20]:
print( "The best accuracy was with", mean_acc.max(), "with k=", mean_acc.argmax()+1) 

The best accuracy was with 0.7012503005530175 with k= 6
